# Constants for CX Setup Interpreter
VERSION               = "v1.0.0"
AUTHOR                = "MF366"
NAME                  = "CX Setup"
LICENSE               = "MIT"
YEAR                  = "2025"
LANGUAGE              = "Python 3"
GITHUB                = "https://github.com/MF366-Coding/ContenterX/blob/main/core/parsers/cxsetup.py"
GITHUB_HOME           = "https://github.com/MF366-Coding/ContenterX"
GITHUB_AUTHOR         = "https://github.com/MF366-Coding"
AUTHOR_URL            = "https://mf366-coding.github.io/"
DOCS_URL              = "https://mf366-coding.github.io/documentation/cxsetup/cxsetup_1.0.html"
